services:
  postgres:
    image: postgres:latest
    container_name: DBcafe
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: cafeDB
    ports:
      - "5431:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - app-network

  cafe:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: cafeDB
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      LOG_LEVEL: INFO
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_db:

networks:
  app-network:
    driver: bridge
    name: cafeNet