spring:
  application:
    name: Cafe
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    repair-on-migrate: true
    validate-on-migrate: false
    enabled: true
    locations: classpath:db/migration
    schemas: public
    default-schema: public

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: ${LOG_LEVEL}

#spring:
#  application:
#    name: Cafe
#  datasource:
#    url: jdbc:postgresql://localhost:5431/cafeDB
#    username: postgres
#    password: 1111
#    driver-class-name: org.postgresql.Driver
#
#  flyway:
#    repair-on-migrate: true
#    validate-on-migrate: false
#    enabled: true
#    locations: classpath:db/migration
#    schemas: public
#    default-schema: public
#
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#logging:
#  level:
#    root: INFO

